server:
  #  port: ${PORT:${SERVER_PORT:8080}}
  port: ${PORT:8081}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msmovie
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**
        - id: mscatalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - StripPrefix=3

info:
  app:
    name: ${spring.application.name}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway